language: julia
os:
#    - osx
    - linux
julia:
    - 1.0
    - 1.1
    - nightly
notifications:
    email: false
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

